name: 'HaxExtend'

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2
        - name: 'Set up Python'
          uses: actions/setup-python@v2
          with:
            python-version: '3.7'
        - name: 'Install requirements'
          run: |
            pip install -r ./requirements.txt
            pip install --user six
#        - name: Install ChromeDriver
#          run: |
#            sudo cp -p ./chromedriver /usr/bin/
#            chmod -R 777 /usr/bin/chromedriver
        - name: 'Working'
          env:
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            BARKKEY: ${{ secrets.BARKKEY }}
          run: |
            python ./main.py
        
